# Generated by Django 4.2.13 on 2024-06-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_user_delete_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
