# Generated by Django 4.2.13 on 2024-06-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_user_is_active_alter_user_email_alter_user_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
