# Generated by Django 4.2.13 on 2024-07-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_user_is_staff_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
