# Generated by Django 4.2.13 on 2024-06-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='users',
        ),
    ]
